a = (input('\033[;1;7;97mDigite algo:\033[m '))
print('O tipo primitivo deste item é', type(a))
print('A informação é numérica?', a.isnumeric())
print('É alfabética?', a.isalpha())
print('O dado é alfanumérico?', a.isalnum())
print('E é um dígito?', a.isdigit())
print('Está minúscula?', a.islower())
print('Ou está escrito em letras maiúsculas?', a.isupper())
print('São apenas espaços?', a.isspace())
print('É possível imprimir?', a.isprintable())
print('O dado é ASCII?', a.isascii())
print('A informação é um identificador?', a.isidentifier())
print('É capitalizado?', a.istitle())
print()
print('Certo, muito obrigada!')
